# Generated by Django 4.2.3 on 2023-09-11 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='ic_correct',
            new_name='is_correct',
        ),
    ]
